### ISSUE TITLE
broke

### ISSUE THREAD

**Issue by kyledhardison** [akump/quote-bot-website#1]
The web site does not display necessary messages.

Kindly do the needful and repair.

Thanks and regards

**Comment by akump** [comment]
@kyledhardison please direct your issues to [@spoondocto](https://github.com/SpoonDoctor/GroupMeAllIn1Bot)

**Comment by cmdavidson** [comment]
Have you tried turning it off and on again?

**Comment by akump** [comment]
Fixed
